### ISSUE TITLE
Error 500 bei Create Package

### ISSUE THREAD

**Issue by berndoberknapp** [hbz/gokb-phase1#17]
Beim Aufruf von Create Package antwortet der Server mit Error 500. Das Problem tritt sowohl beim Staging Server http://phaeton.hbz-nrw.de/gokb/create/index?tmpl=org.gokb.cred.Package als auch beim Entwicklungsserver http://phaeton-dev.hbz-nrw.de/gokb/create/index?tmpl=org.gokb.cred.Package auf.

**Comment by hornmo** [comment]
Vielen Dank für den Hinweis. Habe eine Lösung zum offenen Pull-Request #16 hinzugefügt.

**Comment by philboeselager** [comment]
@berndoberknapp : die beiden oben genannten Links funktionieren jetzt. Bitte um kurze Überprüfung und Schließen des Tickets, sofern keine weiteren Beanstandungen hierzu auftreten.

**Comment by darupp** [comment]
Ticket geschlossen, funktioniert
