### ISSUE TITLE
Datenupload Crossreferencing-API

### ISSUE THREAD

**Issue by lemfra** [hbz/gokb-phase1#4]
- Paket upload: Daten von DeGruyter werden nicht per TIPP mit Titeln verbunden

**Comment by HebisJC** [comment]
Sobald einem JSON-TIPPS-Datensatz Informationen zur Plattform fehlen, tritt das Problem auf.

**Comment by philboeselager** [comment]
@HebisJC : Ist das dann nicht ein Fall von GIGO ?

**Comment by philboeselager** [comment]
@lemfra : in der aktuellen GOKb sind die DeGruyter-Paketdaten sowohl mit TIPPs, als auch darüber mit Titeln verbunden. Ist das Issue damit obsolet? Siehe:

- "yourFavouriteGOKbServer"/gokb/resource/show/org.gokb.cred.Package%3A266486
- "yourFavouriteGOKbServer"/gokb/resource/show/org.gokb.cred.Package%3A678835

**Comment by lemfra** [comment]
In der aktuellen GOKb gelöst.
