### ISSUE TITLE
Error 500 bei Plattformauswahl eines Tipp

### ISSUE THREAD

**Issue by darupp** [hbz/gokb-phase1#7]
Github-Oberfläche: Bei der Auswahl der Plattform (Voreinstellung: empty) eines Tipp liefert der Server eine 500 zurück.

http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.TitleInstancePackagePlatform%3A4237196

**Comment by philboeselager** [comment]
@darupp : konnte nicht mehr reproduziert werden, siehe bspw. 

- http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Platform%3A66559
- http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Platform%3A66712
- http://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Platform%3A200289

Scheint gefixt zu sein. Wenn das Problem nicht reproduziert werden kann, bitte einfach das Ticket schließen.

**Comment by darupp** [comment]
Nicht reproduzierbar, daher geschlossen.
