### ISSUE TITLE
Doppelte Identifers beim Import von Titles

### ISSUE THREAD

**Issue by Moetez16** [hbz/gokb-phase1#9]
Seit dem Branch von Moritz, werden beim Import von Title, die Identifers doppelt erstellt.

**Comment by hornmo** [comment]
Meinst du seit dem letzten Merge von meinem Pull-Request? Weil da an sich nichts an dem Umgang mit Titel-Identifiers geändert wurde. Sind alle Identifiers doppelt, oder nur ein paar?

**Comment by Moetez16** [comment]
Ja nach deinem letzten Merge vermutlich. Du kannst es mal testen wenn du bei dir Title importierst. Vlt ist der Fehler auch nach dem Merge bei uns passiert, aber wir haben nichts geändert beim Integrationen Controller.  

Machmal werden alle Identifiers doppelt, aber manchmal nur ein paar.

**Comment by Moetez16** [comment]
Houskeeping löst das Problem
